name: disk_space_android
description: DiskSpace for Android Platform.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  disk_space_platform_interface:
    path: ../disk_space_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.suamusica.disk_space_android
        pluginClass: DiskSpaceAndroidPlugin
