name: disk_space
description: SM Disk Space.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: disk_space_android
      ios:
        default_package: disk_space_ios

dependencies:
  flutter:
    sdk: flutter

  disk_space_platform_interface:
    git:
      url: https://github.com/SuaMusica/disk_space.git
      path: disk_space_platform_interface/
      ref: enhancement/#1-disk_space
  disk_space_android:
    git:
      url: https://github.com/SuaMusica/disk_space.git
      path: disk_space_android/
      ref: enhancement/#1-disk_space
  disk_space_ios:
    git:
      url: https://github.com/SuaMusica/disk_space.git
      path: disk_space_ios/
      ref: enhancement/#1-disk_space

# dependencies_overrides:
#   disk_space_platform_interface:
#     path: ../disk_space_platform_interface
#   disk_space_android:
#     path: ../disk_space_android
#   disk_space_ios:
#     path: ../disk_space_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.1.2
